# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e4d81c3b9dddb9f76ce82ef1790da0b0291308ed17f3b7e1899a5589634a602a5cb1cfba4f636caa20847b85f0ed86b8dc9d5ecbc32887ab92698279d2d5826d

test:
  secret_key_base: b86dd068d71b3eb5abc6dd949226f7e1ea76157d78ee49ac7867ac9b4d57e1caa789012470de9045b9c83d895b4613c8f1112c6a735af07ea66a6e94661777e0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
